In [1]:
import deepchem as dc
import numpy as np

X = np.random.rand(10, 5) # 10 samples, 5 features each
y = np.random.rand(10, 1) # 10 target values
dataset = dc.data.NumpyDataset(X, y)
print(dataset)

No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!
Skipped loading material featurizer, missing a dependency. No module named 'ase'


Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead


Skipped loading some PyTorch models, missing a dependency. No module named 'transformers'
No module named 'transformers'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'transformers'
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'jax'


<NumpyDataset X.shape: (10, 5), y.shape: (10, 1), w.shape: (10, 1), ids: [0 1 2 3 4 5 6 7 8 9], task_names: [0]>


In [2]:
print(dataset.X.shape, dataset.y.shape)
print(dataset.X)

(10, 5) (10, 1)
[[0.95155564 0.68229633 0.60688278 0.27048162 0.7342297 ]
 [0.27262458 0.76024581 0.99491117 0.35903423 0.30308216]
 [0.89929656 0.37156579 0.41692583 0.62299127 0.67351989]
 [0.60184334 0.07652324 0.60757646 0.18396527 0.05653997]
 [0.00768474 0.36389976 0.01018365 0.00442939 0.96726372]
 [0.56305188 0.27275169 0.6508384  0.62111369 0.58600117]
 [0.57181092 0.07777815 0.96947656 0.60059594 0.05313261]
 [0.06910167 0.67668565 0.33375673 0.21999349 0.52298234]
 [0.81042144 0.01095236 0.05360613 0.25458294 0.71094353]
 [0.99386073 0.87535041 0.69862189 0.61007372 0.21404896]]


In [3]:
from sklearn.ensemble import RandomForestRegressor

sklearn_model = RandomForestRegressor(n_estimators=100)
model = dc.models.SklearnModel(sklearn_model)
model.fit(dataset)

In [4]:
predictions = model.predict(dataset)
print(predictions[:5])

metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)
score = model.evaluate(dataset, [metric])
print(score)

[0.59681538 0.20527899 0.3433555  0.46270888 0.86575243]
{'pearson_r2_score': 0.9202947255320193}


In [5]:
import sys
import tensorflow as tf
print(sys.version)

3.11.16 (main, Aug 12 2026, 23:03:19) [Clang 17.0.0 (clang-1700.6.4.2)]
